{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default "fintech" }}
  labels:
    name: {{ .Release.Namespace | default "fintech" }}
    environment: {{ .Values.global.environment }}
    managed-by: helm
  {{- end }}