apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "fintech_analytics"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fintech
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: fintech
data:
  01-init.sql: |
    CREATE SCHEMA IF NOT EXISTS analytics;
    
    -- Создаем пользователя для приложения (опционально)
    CREATE USER analytics_user WITH PASSWORD 'analytics_pass';
    
    -- Даем права на схему
    GRANT ALL PRIVILEGES ON SCHEMA analytics TO analytics_user;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO analytics_user;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA analytics TO analytics_user;
    
    -- Даем права пользователю postgres тоже
    GRANT ALL PRIVILEGES ON SCHEMA analytics TO postgres;