{{- if not .Values.database.passwordFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fintech-analytics.fullname" . }}-db-secret
  namespace: {{ .Release.Namespace | default "fintech" }}
  labels:
    {{- include "fintech-analytics.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
  {{- end }}